Pruebe cambiano el yaml:

name: SECOP Automatizado

on:
  schedule:
    - cron: '0 11 * * *'
  workflow_dispatch:

permissions:
  contents: write

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  run-secoppipeline:
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Clonar repositorio
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: 🐍 Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: 📦 Instalar librerías
        run: |
          pip install --upgrade pip
          pip install pandas requests pyarrow

      - name: 🚀 Ejecutar descarga 3 meses
        run: python scripts/descarga_3mes_datos.py

      - name: 💾 Subir cambios automáticamente
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"

          git add .
          git diff --staged --quiet && exit 0

          git commit -m "Actualización automática datos SECOP"
          git pull --rebase origin main
          git push origin HEAD:main
